apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-basic-169935392
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/fw8s5bhq-tenant/test-app-169935392/python-basic-169935392@sha256:5c17ea565f4ff53b2c0d857177a3fe7fc27be7ac9cc60591dd34c727fb17fc85
        name: my-python
        resources: {}
status: {}
