apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-169935392
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-169935392
    app.kubernetes.io/part-of: test-app-169935392
  name: python-basic-169935392
spec:
  rules:
  - host: python-basic-169935392-fw8s5bhq-tenant.apps.hac-devsandbox.5unc.p1.openshiftapps.com
    http:
      paths:
      - backend:
          service:
            name: python-basic-169935392
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
