apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-169935392
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-169935392
    app.kubernetes.io/part-of: test-app-169935392
  name: python-basic-169935392
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-169935392
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-169935392
    spec:
      containers:
      - image: quay.io/hacdev/fw8s5bhq-tenant/test-app-169935392/python-basic-169935392@sha256:5c17ea565f4ff53b2c0d857177a3fe7fc27be7ac9cc60591dd34c727fb17fc85
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
